{% set name = "pytokens" %}
{% set version = "0.2.0" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 532d6421364e5869ea57a9523bf385f02586d4662acbcc0342afd69511b4dd43

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  skip: True  # [py<38]

requirements:
  host:
    - python
    - pip
    - setuptools
  run:
    - python

test:
  source_files:
    - tests
  imports:
    - pytokens
  requires:
    - pytest
    - pip
  commands:
    - pip check
    - pytest tests

about:
  home: https://github.com/tusharsadhwani/pytokens
  dev_url: https://github.com/tusharsadhwani/pytokens
  doc_url: https://github.com/tusharsadhwani/pytokens/blob/main/README.md
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: "A fast, spec-compliant Python tokenizer"
  description: |
    A fast, spec-compliant Python tokenizer that runs on older Pythons.